### ISSUE TITLE
Cant import json

### ISSUE THREAD

**Issue by xblomx** [globaldyne/parfumvault#162]
**Describe the bug**
Importing a backup of a fragrance from json, doesnt show up.

**To Reproduce**
1. Go to '...' Formulas management
2. Click on '....' Formulas
3. Scroll down to '....' go to the right click actions, import formulas from json
4. See error it does not show up

**Expected behavior**
I expect to see the formular imported

**Screenshots**

**Please complete the following information:**
 - Platform: [e.g. docker] docker
 - Browser [e.g. chrome, safari] all browsers
 - PV Version [e.g. 9.1] 9.7

**Additional context**
Add any other context about the problem here, also provide details regarding your installation.

**Comment by globaldyne** [comment]
Please provide the json file as well

**Comment by xblomx** [comment]
Could Ibsend that directly to your email?

Not sharing it to everyone?

. xblomx

**Comment by globaldyne** [comment]
Its better here so it can be properly tracked as a bug. 
To avoid sharing full data you can set quantities to fake number eg: 100
or
Create a dummy formula
Test that problem persists
and share it here

**Comment by xblomx** [comment]
Attached all is set at 100

. xblomx

**Comment by globaldyne** [comment]
no file attached

**Comment by xblomx** [comment]
It was attached as json

But I have fiddæwd around and found out that importing it over writes the original formular.

So I made a formular called test 1 and made a copy of it and called it test 1 - #2 and made a backup of that and made another called test 1 - #3

Had to restore the #2 and it over writes the #3

Etc...

So it got solved with me making a copy of #3 and importing #2 and it over writes #3 that I now have a copy of...

Hope it makes sense... But it basically over writes for some reason...

. xblomx

**Comment by globaldyne** [comment]
unfortunately can't tell if idon't see the file, wan't attached on your previous message

**Comment by xblomx** [comment]
Attached again

. xblomx

**Comment by globaldyne** [comment]
Still not attached, if you replying via email, won't work. Use the browser instead

**Comment by xblomx** [comment]
[test formular.json](https://github.com/globaldyne/parfumvault/files/14795596/test.formular.json)

**Comment by xblomx** [comment]
Done

. xblomx

**Comment by globaldyne** [comment]
Imports successfully, no issues

**Comment by xblomx** [comment]
Yes but did you see my response a few mails back...

. xblomx

**Comment by globaldyne** [comment]
No to sure i understand the issue, you said you can't import the formula but that's not the case.

**Comment by xblomx** [comment]
Well, I have a similar formular that I made a copy of, and made some cnages to, and then when importing this, somehow it over writes.

I did not see it initially because it doesnt import with the name given but over writes the one it was a copy of.


. xblomx

**Comment by globaldyne** [comment]
Confirmed JSON import works as expected.
